site_name: Stakater Actions
docs_dir: content
site_url: https://docs.stakater.com/actions/
repo_url: https://github.com/stakater/actions-docs
edit_uri: blob/main/content/
use_directory_urls: false
strict: true
theme:
    name: material
    logo: assets/images/favicon.svg
    favicon: assets/images/favicon.svg
    custom_dir: custom_theme/
    palette:
        primary: white

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
    analytics:
        provider: google
        property: G-TTH1YYW5TX
    consent:
        title: Cookie consent
        actions:
            - accept
            - reject
            - manage
        description: >-
            Stakater uses cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.

nav:
    - Actions:
        - index.md
    - Documentation: https://docs.stakater.com/
    - Stakater Home: https://www.stakater.com/
    - SAAP: https://www.stakater.com/saap-kubernetes-openshift
    - Consultancy: https://www.stakater.com/kubernetes-consultancy
    - Events: https://www.stakater.com/events
    - Platform Assessment: https://www.stakater.com/kubernetes-platform-assessment
    - Careers: https://www.stakater.com/careers

plugins:
    - search
